spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ra_dev
    username: ra_dev_user
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true